### ISSUE TITLE
7/7 Task Ideas

### ISSUE THREAD

**Issue by vjrodriguez** [Bookmarkers/markjoy#60]
- [x] the npm run start-dev bug in sw.js #50 

- [x] generateSW bug with changing file paths #51 

- [x] In seed.js, addBookmarks and addGoals on users. addGoals to categories etc.

- [x] deploy on Heroku + Travis #47 

- [x] Goal & User routes #65 

- [x] Bookmark routes #63
