### ISSUE TITLE
7/8 Task Ideas:

### ISSUE THREAD

**Issue by vjrodriguez** [Bookmarkers/markjoy#93]
- [x] Debug component render issue with login and signup #86 #74 

- [x] Header (i.e. Navbar) UI #96 

- [x] Landing page UI #73 

- [x] Goal (VR) #97 #98

- [ ] Bookmark view (YJ) #99

- [ ] User main page (goals, all bookmarks, sidebar for categories) #100

- [x] Auth(login and sign up) routes and frontend

- [x] Chrome API to import user bookmarks?

- [ ] Travis CI (do not use node 14!Node 12 is good)
